/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeOldImport } from './routes/homeOld'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const HomeOldRoute = HomeOldImport.update({
  path: '/homeOld',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/homeOld': {
      id: '/homeOld'
      path: '/homeOld'
      fullPath: '/homeOld'
      preLoaderRoute: typeof HomeOldImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, HomeOldRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/homeOld"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/homeOld": {
      "filePath": "homeOld.ts"
    }
  }
}
ROUTE_MANIFEST_END */
